Fix functional test failure under python 3
Wrapping dict.keys() in list() to remove error:
TypeError: 'dict_keys' object does not support indexing.

Change-Id: Ic8a1818eafcedec226798bb8a434c31a18d45d67
Closes-Bug: #1557214