Raise NotImplementedError instead of NotImplemented
NotImplementedError is the name of the exception
(https://docs.python.org/2/library/exceptions.html).

NotImplemented is the name of a constant
(https://docs.python.org/2/library/constants.html).

>>> raise NotImplemented()
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    raise NotImplemented()
TypeError: 'NotImplementedType' object is not callable

>>> raise NotImplementedError()
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    raise NotImplementedError()
NotImplementedError

This patch fix it.

Change-Id: Ia6157f1137300a6c5c4c0e52fd1a46ccc29a9564
Closes-Bug: #1339855